### ISSUE TITLE
Android Crash Error while updating property 'allowsFullscreenVideo' of a view managed by: RNCWebView

### ISSUE THREAD

**Issue by omrip2** [react-native-webview/react-native-webview#1589]
**Bug description:**
I have an application on production and recently I updated the application in the store with an new feature which containing WebView.
Since then I see many crashes on crashlyitcs with the following description:
Error while updating property 'allowsFullscreenVideo' of a view managed by: RNCWebView

Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'allowsFullscreenVideo' of a view managed by: RNCWebView
       at com.facebook.react.uimanager.z0$k.a(:122)
       at com.facebook.react.uimanager.x0$c.a(:10)
       at com.facebook.react.uimanager.x0.a(:36)
       at com.facebook.react.uimanager.ViewManager.updateProperties(:14)
       at com.facebook.react.uimanager.k.a(:53)
       at com.facebook.react.uimanager.t0$e.execute(:23)
       at com.facebook.react.uimanager.t0$a.run(:46)
       at com.facebook.react.uimanager.t0.i(:53)
       at com.facebook.react.uimanager.t0.i()
       at com.facebook.react.uimanager.t0$b.runGuarded(:2)
       at com.facebook.react.bridge.GuardedRunnable.run()
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7156)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Environment:**
Android versions: 8, 9, 10
"react-native": "0.61.5"
"react-native-webview": "^9.0.2"

**Comment by krunalbad** [comment]
Any updates on this?

**Comment by sai13mogli** [comment]
still searching for the solutions.

**Comment by pinpolygons** [comment]
Any solution for this issue?

**Comment by k-sav** [comment]
_still searching_ in 2021

**Comment by aamir-ans** [comment]
@k-sav Have you tried by adding  **android:hardwareAccelerated="true**  in android manifest file ???

**Comment by darriuk** [comment]
## Status
Yep, still an issue as of FEB 2022

## Environment
- device: HUAWEI
- model: TAS-L29
- orientation: portrait
- OS: android
- OS version: 10
- runtime version: ```[{
  "androidApiLevel": "29",
  "osBuild": "TAS-L29 11.0.0.151(C636E6R7P5)",
  "reactNative": "0.66.2",
  "reactNativeJsEngine": "hermes"
}]()```
- DPI: 480
- Screen density: 3
- Resolution: 2259x1080
- Free memory: 518.5 MB

## Bug description
Crashing app at some unknown point. Possibly relating to video playback.

Stacktrace from BugSnag...

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'allowsFullscreenVideo' of a view managed by: RNCWebView
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:143)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:76)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:909)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:984)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8387)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:143)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:76)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:909)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:984)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8387)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.getRequestedOrientation()' on a null object reference
        at com.reactnativecommunity.webview.RNCWebViewManager.setupWebChromeClient(RNCWebViewManager.java:712)
        at com.reactnativecommunity.webview.RNCWebViewManager.setAllowsFullscreenVideo(RNCWebViewManager.java:576)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:143)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:76)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:909)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:984)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8387)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by kalyaniDM** [comment]
Any update to solve this issue as I am getting this in react-native-webview 11.14.3 version.

**Comment by kalyaniDM** [comment]
Hi Any update as we will need to solve this on urgent basis , please let me know if anyone got the solution for the above issue.

**Comment by Aure77** [comment]
Issue still present. @Titozzz / @jamonholmgren / @asklar / @chiaramooney : can you re-open this issue ?

**Comment by tarkcelk** [comment]
> @k-sav Have you tried by adding **android:hardwareAccelerated="true"** in android manifest file ???

it worked, thanks
