### ISSUE TITLE
Upload files don't work properly in Android

### ISSUE THREAD

**Issue by danigm87** [react-native-webview/react-native-webview#1697]
**Bug description:**
Upload files don't work properly in Android, the app is crashing while I am trying to select a file, shot a photo or video, or only opening the selector modal and closing it.

**To Reproduce:**
Use this example:
https://github.com/react-native-webview/react-native-webview/blob/4093682e08a7a047de39046e8e48d9a78b2ad0f2/example/examples/Uploads.tsx#L6

**Expected behavior:**
Should select a file from camera or file manager.

**Screenshots/Videos:**
![Oct-13-2020 18-48-57](https://user-images.githubusercontent.com/14923858/95891248-1e97ac00-0d85-11eb-88bb-66416e351a0a.gif) ![opening_and_close_modal](https://user-images.githubusercontent.com/14923858/95891781-d75deb00-0d85-11eb-8e10-3c0ee6404873.gif)

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 0.62
 - react-native-webview version: Tested in some versions (latest too)

**Comment by danigm87** [comment]
I only could log an error while I was debugging this problem, I think could be helpful

`Uncaught Error: Extension context invalidated.
    at Object.value [as sendMessage] (polyfill.js:124)
    at HTMLDocument.<anonymous> (include.postload.js:683)
value @ polyfill.js:124
(anonymous) @ include.postload.js:683`

**Comment by danigm87** [comment]
Error while getting photo from camera and press ✔️ :

`D/EGL_emulation: eglMakeCurrent: 0xebb33440: ver 3 0 (tinfo 0xc7496200)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.projectname.app, PID: 14123
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent {  }} to activity {com.projectname.app/com.mobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.reject(java.lang.String, java.lang.String)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.reject(java.lang.String, java.lang.String)' on a null object reference
        at com.dyneti.dyscan.reactnative.RNDyScanModule.onActivityResult(RNDyScanModule.java:116)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:288)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:738)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
I/Process: Sending signal. PID: 14123 SIG: 9
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'`

**Comment by danigm87** [comment]
Error while selecting a photo from gallery:

        `D/AndroidRuntime: Shutting down VM`
    `E/AndroidRuntime: FATAL EXCEPTION: main`
        `Process: com.thanxsandbox.pincho, PID: 14474`
        `java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:25 flg=0x1 }} to activity {com.thanxsandbox.pincho/com.mobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.reject(java.lang.String, java.lang.String)' on a null object reference`
            `at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)`
            `at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)`
            `at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)`
            `at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)`
            `at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)`
            `at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)`
            `at android.os.Handler.dispatchMessage(Handler.java:107)`
            `at android.os.Looper.loop(Looper.java:214)`
            `at android.app.ActivityThread.main(ActivityThread.java:7356)`
            `at java.lang.reflect.Method.invoke(Native Method)`
            `at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)`
            `at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`
        `Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.reject(java.lang.String, java.lang.String)' on a null object reference`
            `at com.dyneti.dyscan.reactnative.RNDyScanModule.onActivityResult(RNDyScanModule.java:116)`
            `at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:288)`
            `at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:738)`
            `at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)`
            `at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)`
            `at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)`
            `at android.app.Activity.dispatchActivityResult(Activity.java:8110)`
            `at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)`
            `at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) `
            `at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) `
            `at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) `
            `at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) `
            `at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) `
            `at android.os.Handler.dispatchMessage(Handler.java:107) `
            `at android.os.Looper.loop(Looper.java:214) `
            `at android.app.ActivityThread.main(ActivityThread.java:7356) `
            `at java.lang.reflect.Method.invoke(Native Method) `
            `at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) `
            `at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `
    `I/Process: Sending signal. PID: 14474 SIG: 9`
    `Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'`

**Comment by danigm87** [comment]
Solved: This was a problem with other library (dyscan) that was overriding the onActivityResult with the same requestCode than react-native-webview library.

**Comment by DukazzCruz** [comment]
> Solved: This was a problem with other library (dyscan) that was overriding the onActivityResult with the same requestCode than react-native-webview library.

@daaanigm Hi, how can you resolve it?

**Comment by daaanigm** [comment]
> > Solved: This was a problem with other library (dyscan) that was overriding the onActivityResult with the same requestCode than react-native-webview library.
> 
> 
> 
> @daaanigm Hi, how can you resolve it?

I needed to modify the library and return a different code in the onActivityResult method. 

I don't remember well because I worked on this some years ago but I remember that was the solution
