### ISSUE TITLE
Android hard crash with blob:// links

### ISSUE THREAD

**Issue by TiavinaRakotobe** [react-native-webview/react-native-webview#1821]
- react-native-webview version: 11.0.2

**Comment by kailashchand-arcgate** [comment]
After upgrade version  from 8.0.6 to 11.3.2 but still getting app crash. our app is based on below dependencies : 
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-webview": "^11.3.2",
Android version : 11.0
Crash Logs 
```
Fatal Exception: java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: blob:https://www.emerald.com/e76b0f3e-c7db-4740-8dda-5c724e8b7981
       at android.app.DownloadManager$Request.<init>(DownloadManager.java:497)
       at com.reactnativecommunity.webview.RNCWebViewManager$2.onDownloadStart(RNCWebViewManager.java:199)
       at Ct.handleMessage(chromium-Monochrome.aab-stable-438910523:155)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
