### ISSUE TITLE
Unable to test within react-native-view on Windows

### ISSUE THREAD

**Issue by zwang** [react-native-webview/react-native-webview#1822]
**Bug description:**
I am trying to run the test with in react-native-view on windows by following this: https://github.com/react-native-webview/react-native-webview/blob/HEAD/docs/Contributing.md

However, I got error after I ran `yarn start:windows`

```
error Invalid regular expression: /(C:\\Users\\zhaow\\source\\react-native-webview\\node_modules\\react-native\\.*|C:\\Users\\zhaow\\source\\react-native-webview\\windows.*|.*\.ProjectImports\.zip|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(C:\\Users\\zhaow\\source\\react-native-webview\\node_modules\\react-native\\.*|C:\\Users\\zhaow\\source\\react-native-webview\\windows.*|.*\.ProjectImports\.zip|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\Users\zhaow\source\react-native-webview\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at Object.<anonymous> (C:\Users\zhaow\source\react-native-webview\metro.config.windows.js:29:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at module.exports (C:\Users\zhaow\source\react-native-webview\node_modules\cosmiconfig\node_modules\import-fresh\index.js:28:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce:**
1. Clone the project, get latest on master branch
2. At root folder, run `yarn install`
3. Then run `yarn start:windows`

**Expected behavior:**
There should be no error, and the test run successfully

**Screenshots/Videos:**
![react-native-webview windows issue](https://user-images.githubusercontent.com/1171212/104499351-d65d7500-5591-11eb-9e52-945e71f56dae.PNG)

**Environment:**
 - OS: Windows 10 Pro
 - OS version: 20H2 (19042.746)
 - react-native version: 0.62.5
 - react-native-webview version: 11.0.3 (https://github.com/react-native-webview/react-native-webview/commit/6880289796021a08aaa69abd2d6e522eb7b305c7)

**Comment by schteff** [comment]
@zwang did you find a solution? I'm having the same problem.

**Comment by zwang** [comment]
@schteff  sorry, I didn't find a solution for this. I moved on as I decided not to use this anymore since I could not even get demo to work.
