### ISSUE TITLE
Blob url not working in android only

### ISSUE THREAD

**Issue by kailashchand-arcgate** [react-native-webview/react-native-webview#1945]
## Issue : 
After upgrade version from **8.0.6 to 11.3.2** but still getting app crash. we have tested our app in android (10 ) and **iOS simulator** (iphone 11 pro, 14.1) both and found our app is crashing in android only. 
## Dependencies 
Our app is based on below dependencies :
- "react": "16.13.1",
- "react-native": "0.63.4",
- "react-native-webview": "^11.3.2",
- Android version : 11.0

## Crash Logs
```sh
Fatal Exception: java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: blob:https://www.emerald.com/e76b0f3e-c7db-4740-8dda-5c724e8b7981
       at android.app.DownloadManager$Request.<init>(DownloadManager.java:497)
       at com.reactnativecommunity.webview.RNCWebViewManager$2.onDownloadStart(RNCWebViewManager.java:199)
       at Ct.handleMessage(chromium-Monochrome.aab-stable-438910523:155)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by JordaoViktor** [comment]
same problem here dude!

**Comment by JordaoViktor** [comment]
i have the same problem too!

**Comment by JordaoViktor** [comment]
i still with that lib, but i am making the workaround which opacity: 0.99 and androidLayerType="hardware" mixedContentMode="always", but that solution is not what i expected but works. I also saw in some issues here that you can use react-native-inappbrowser-reborn if helps in your case.

**Comment by TheAlmightyBob** [comment]
This is technically a duplicate of #1090, but unfortunately that one was automatically closed by the github-actions bot (even though there was still activity on it.... I am not a fan of that bot)

There've been a few PRs attempting to resolve this: #1546 , #1817
