### ISSUE TITLE
Attempt to invoke virtual method 'int android.app.Activity.getRequestedOrientation()' on a null object reference

### ISSUE THREAD

**Issue by andmau90** [react-native-webview/react-native-webview#2072]
**Bug description:**
Firebase report the following exception on some devices:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.getRequestedOrientation()' on a null object reference
       at com.reactnativecommunity.webview.RNCWebViewManager.setupWebChromeClient(RNCWebViewManager.java:644)
       at com.reactnativecommunity.webview.RNCWebViewManager.setAllowsFullscreenVideo(RNCWebViewManager.java:511)
```

**To Reproduce:**
I'm unable to reproduce it

**Environment:**
 - OS: Android
 - OS version: random
 - react-native version: ^0.63.4
 - react-native-webview version: ^11.6.2

**Comment by KingAmo** [comment]
same here

**Comment by yorickshan** [comment]
same here

**Comment by JairajJangleSLIOT** [comment]
Faced the same issue out of nowhere on version `11.26.1`

Stacktrace:
```
RNCWebViewManager.java:1882 com.reactnativecommunity.webview.RNCWebViewManager$RNCWebView.getId
RNCWebViewManager.java:1222 com.reactnativecommunity.webview.RNCWebViewManager$RNCWebViewClient.createWebViewEvent
RNCWebViewManager.java:1798 com.reactnativecommunity.webview.RNCWebViewManager$RNCWebView$1.run
Handler.java:942 android.os.Handler.handleCallback
Handler.java:99 android.os.Handler.dispatchMessage
Looper.java:240 android.os.Looper.loopOnce
Looper.java:351 android.os.Looper.loop
ActivityThread.java:8381 android.app.ActivityThread.main
Method.java:-2 java.lang.reflect.Method.invoke
RuntimeInit.java:584 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
ZygoteInit.java:1013 com.android.internal.os.ZygoteInit.main
```
