### ISSUE TITLE
App crashes when uploading an image using webview (Android only)

### ISSUE THREAD

**Issue by lfaz** [react-native-webview/react-native-webview#2182]
Whenever you try to upload a file (tried with image) into webview the app crashed with the following error:

```
FATAL EXCEPTION: main
Process: fi.hsl.appdev, PID: 15154
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:32 flg=0x1 }} to activity {fi.hsl.appdev/fi.hsl.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Happens only on Android, real device and emulator and I have react-native-webvew v.11.0.0

Issue related: https://github.com/react-native-webview/react-native-webview/issues/1121

**Comment by AlexanderLanderos** [comment]
Any update to this?

**Comment by antonioHabits** [comment]
the same problem yet

**Comment by mmr94** [comment]
Any update to this?

**Comment by mmr94** [comment]
to all those who had the same problem in my case the problem did not come from react native webview but rather from another package which used onActivityResult and which did not check if the response was really for its package 

check your stacktrace e depth to check who received the onActivityResult method
