### ISSUE TITLE
webview 11.15 crash on android

### ISSUE THREAD

**Issue by 06065044** [react-native-webview/react-native-webview#2282]
java.lang.IncompatibleClassChangeError: The method 'void com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(com.facebook.react.uimanager.events.Event)' was expected to be of type virtual but instead was found to be of type interface (declaration of 'com.reactnativecommunity.webview.RNCWebViewManager' 

at com.reactnativecommunity.webview.RNCWebViewManager.dispatchEvent(RNCWebViewManager.java:168)
        at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebChromeClient.onProgressChanged(RNCWebViewManager.java:1153)
        at com.android.webview.chromium.WebViewContentsClientAdapter.onProgressChanged(WebViewContentsClientAdapter.java:250)
        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:210)

**Comment by luiztools** [comment]
The same here. When using Expo Go on Android 12 the React Native WebView v11.15 crashes the app. When using Expo Go on Android 9 and iOS 15.1, it works perfectly.

**Comment by luiztools** [comment]
Using WebView with style={{ opacity: 0.99, overflow: 'hidden' }} worked for me, as pointed in another thread here on GitHub. Tested with RN WebView v11.15, Expo 43.0.2 in Android v7, v9 and v12.

**Comment by abdullahkhalil2** [comment]
The above given answers doesn't help and issue is still open.
