### ISSUE TITLE
Debugging webview for Android in Chrome inspect tab with Expo

### ISSUE THREAD

**Issue by JeremyColton** [react-native-webview/react-native-webview#2341]
I'm using Expo with your plugin for the webview.
My Android emulator has USB debugging enabled.
It's Android 9 and the WebView implementation is Chrome.

When I go to the inspect tab in Chrome via chrome://inspect/#devices I see this:
![Capture](https://user-images.githubusercontent.com/2919478/150399393-e976c4fe-c0c4-41f6-b4ea-0d91a354b518.PNG)

There's no link to the webview where my code is running so I can't inspect the javascript and html or see why network requests may fail for the webview.

I read here https://forums.expo.dev/t/cant-debug-webview-in-device-on-android-without-detaching/10153 that I need to eject Expo in order to set:

`WebView.setWebContentsDebuggingEnabled(true);`

This apparently can't be set via a boolean flag in the <WebView> tag.

So can you please create a version of your plugin where 'setWebContentsDebuggingEnabled(true)' is used by default, perhaps with an installation property? I desperately need to debug my webview with Expo as the wrapper.

**Comment by JeremyColton** [comment]
After 2 days of experimenting this is how I managed to debug the webivew in Chrome on my laptop of the webview running on my Android phone:

1. Ensure USB debugging is enabled on the device
2. Ensure the WebView implementation is Chrome on the device

3. In my Webstorm, in the project's terminal I wrote:
`expo run:android`
This added the /android folder to my project and all of the dependencies to run the Android app.

4. I navigated to /android/app/src/man/java/com/<project name>/MainApplication.java and edited it as follows:

```
import android.webkit.WebView



public void onCreate() {
    super.onCreate();
    WebView.setWebContentsDebuggingEnabled(true);
    SoLoader.init(this, /* native exopackage */ false);




}
```

5. In the terminal type again:
`expo run:android`

It opened the app on my Android phone still in the Expo app
I waited for the WebView to open and show my page

6. I visited in my laptop's Chrome browser:
chrome://inspect/#devices

I saw the link to let me inspect the webview:
![Capture](https://user-images.githubusercontent.com/2919478/150651560-772b5f05-1d6f-416c-a591-6c4325bfdd09.PNG)

Clicking the link showed the Chrome inspect tab of my webview running on my Android phone!

**Comment by fabiooshiro** [comment]
I got this error
```
expo run:android
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (5.3.0).                 │
│   You are currently using expo-cli 5.0.3                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
› Building app...
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/Users/oshiro/calindra/blockchain/magic_wallet/android/settings.gradle' (/Users/oshiro/.gradle/caches/6.9/scripts/cwftl8rsl0fm4q8tr6zbofeip).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
/Users/oshiro/calindra/blockchain/magic_wallet/android/gradlew exited with non-zero code: 1
Error: /Users/oshiro/calindra/blockchain/magic_wallet/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/oshiro/.nvm/versions/node/v16.13.1/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/Users/oshiro/.nvm/versions/node/v16.13.1/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/Users/oshiro/.nvm/versions/node/v16.13.1/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:18)
    at assembleAsync (/Users/oshiro/.nvm/versions/node/v16.13.1/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/Users/oshiro/.nvm/versions/node/v16.13.1/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:143:9)
```
Im downgraded to java 8 with sdkman
https://sdkman.io/install
```
sdk install java 8.0.322-zulu
```

```
yes | ~/Library/Android/sdk/tools/bin/sdkmanager --licenses
```

**Comment by fabiooshiro** [comment]
before I got this error:
```
expo run:android
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (5.3.0).                 │
│   You are currently using expo-cli 5.0.3                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
› Building app...
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.9/userguide/gradle_daemon.html
Process command line: /Users/oshiro/.sdkman/candidates/java/17.0.1-tem/bin/java -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country=BR -Duser.language=en -Duser.variant -cp /Users/oshiro/.gradle/wrapper/dists/gradle-6.9-all/dooywd8nv05k16orzxge2b1bs/gradle-6.9/lib/gradle-launcher-6.9.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.9
Please read the following process output to find out more:
-----------------------
Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
/Users/oshiro/calindra/blockchain/magic_wallet/android/gradlew exited with non-zero code: 1
Error: /Users/oshiro/calindra/blockchain/magic_wallet/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/oshiro/.nvm/versions/node/v16.13.1/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/Users/oshiro/.nvm/versions/node/v16.13.1/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/Users/oshiro/.nvm/versions/node/v16.13.1/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:18)
    at assembleAsync (/Users/oshiro/.nvm/versions/node/v16.13.1/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/Users/oshiro/.nvm/versions/node/v16.13.1/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:143:9)
```
I edited the `gradle.properties` file inside android folder removing the  `-XX:MaxPermSize=512m flag`

**Comment by realfresh** [comment]
For anyone here using managed expo but don't want to eject. If you use EAS build service. You can create the following plugin

```
import type { ConfigPlugin } from "@expo/config-plugins";
import { withMainApplication } from "@expo/config-plugins";

const plugin: ConfigPlugin = (expoConfig) => {
  return withMainApplication(expoConfig, (modConfig) => {
    let contents = modConfig.modResults.contents.replace(
      /public void onCreate\(\) \{\n((.|\n)*?)\}\n\n/,
      `public void onCreate() {\n$1\n    WebView.setWebContentsDebuggingEnabled(true);\n  }\n\n`
    );
    const index = contents.indexOf("public class MainApplication");
    contents =
      contents.slice(0, index) + `import android.webkit.WebView;\n\n` + contents.slice(index);
    modConfig.modResults.contents = contents;
    // console.log(contents);
    return modConfig;
  });
};

export default plugin;
```

Compile the typescript code above.

Then add it to your expo config plugins

```
"plugins": ["./android-webview-debug.js"]
```

**Comment by vinayn-mend** [comment]
@realfresh Can you explain the steps? I have created a file like this in the root folder. Added the plugin inside app.json file. What' the next step?

**Comment by srosato** [comment]
with Expo SDK v50, it seems to be generating Kotlin code instead, so I modified @realfresh plugin like so to make it work again:

```javascript
const { withMainApplication } = require("@expo/config-plugins");

const plugin = (expoConfig) => {
  return withMainApplication(expoConfig, (modConfig) => {
    let contents = modConfig.modResults.contents.replace(
      /override fun onCreate\(\) \{\n((.|\n)*?)\}\n\n/,
      `override fun onCreate() {\n$1\n    WebView.setWebContentsDebuggingEnabled(true);\n  }\n\n`
    );
    const index = contents.indexOf("class MainApplication");
    contents = contents.slice(0, index) + `import android.webkit.WebView;\n\n` + contents.slice(index);
    modConfig.modResults.contents = contents;
    return modConfig;
  });
};

module.exports = plugin;
```

**Comment by uffe** [comment]
Cool config plugin, just getting into using them. 
But I found that it is not needed anymore, as the webviewDebuggingEnabled prop can be set true on the WebView component is enough.
