### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider com.reactnativecommunity.webview.RNCWebViewFileProvider: java.lang.NullPointerException

### ISSUE THREAD

**Issue by the-kool-sk** [react-native-webview/react-native-webview#2456]
**Bug description: **
2022-04-25 19:07:04.655 1355-1355 E/AndroidRuntime: FATAL EXCEPTION: main

    java.lang.RuntimeException: Unable to get provider com.reactnativecommunity.webview.RNCWebViewFileProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at android.app.ActivityThread.installProvider(ActivityThread.java:7244)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleInstallProvider(ActivityThread.java:3835)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at androidx.core.content.FileProvider.attachInfo(FileProvider.java:416)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780) 
        at android.app.ActivityThread.handleInstallProvider(ActivityThread.java:3835) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 

**To Reproduce:**
1. Start a foreground service on LOCKED_BOOT_COMPLETED received.
2. Restart device, make sure your service is running.
3. Enter password/pattern/pin 
4. You will see the exception in the stack trace.

**Expected behavior:**
There should not be an exception.

**Screenshots/Videos:**
NA

**Environment:**
 - OS: Android
 - OS version: Android 11
 - react-native version: api 'com.facebook.react:react-native:+'
 - react-native-webview version: "react-native-webview@7.4.1"

**Comment by lundjrl** [comment]
I know this is closed out but if anyone is running into this issue, installing version 11.23.0 solved it for me.

**Comment by durgeshtimbadiya** [comment]
Still getting same error any advise please.
