### ISSUE TITLE
Crash InvocationTargetException on Samsung Galaxy S10 (android 12)

### ISSUE THREAD

**Issue by GaelCO** [react-native-webview/react-native-webview#2514]
Hi,

A crash occurs on the Samsung Galaxy S10 in android 12  (8 differents users). If I believe the logs, it comes from a problem to loading the native webview libraries. 
I don't know if you can do anything on your side to solve this issue or if only an intervention on the affected device can solve the problem.

This issue looks like this old one : https://github.com/react-native-webview/react-native-webview/issues/1060

**Environment:**
 - OS: android 12
 - react-native version: 0.67.4
 - react-native-webview version: 11.8.2

Main log : 
`Fatal Exception: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
       at android.webkit.CookieManager.getInstance(CookieManager.java:50)
       at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:10)
       at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java)
       at com.facebook.react.modules.websocket.WebSocketModule.getCookie(WebSocketModule.java:16)
       at com.facebook.react.modules.websocket.WebSocketModule.connect(WebSocketModule.java:47)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:148)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:147)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:37)
       at java.lang.Thread.run(Thread.java:920)`

Load log : 
`Caused by java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~konySwt1HDgqW5_LXRGBoQ==/com.google.android.webview-qlba5Tg1jkJRuOprPYZObQ==/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1656)
       at org.chromium.base.library_loader.b.g(b.java:816)
       at org.chromium.base.library_loader.b.i(b.java:696)
       at org.chromium.android_webview.AwBrowserProcess.h(AwBrowserProcess.java:680)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:441)
       at com.android.webview.chromium.WebViewChromiumFactoryProviderForS.<init>(WebViewChromiumFactoryProviderForS.java:13)
       at com.android.webview.chromium.WebViewChromiumFactoryProviderForS.create(WebViewChromiumFactoryProviderForS.java:9)
       at java.lang.reflect.Method.invoke(Method.java)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:355)
       at android.webkit.CookieManager.getInstance(CookieManager.java:50)
       at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:10)
       at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java)
       at com.facebook.react.modules.websocket.WebSocketModule.getCookie(WebSocketModule.java:16)
       at com.facebook.react.modules.websocket.WebSocketModule.connect(WebSocketModule.java:47)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:148)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:147)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:37)
       at java.lang.Thread.run(Thread.java:920)`

**Comment by ashu8786** [comment]
Even I'm facing the same issue. Did you get any solution yet?

**Comment by GaelCO** [comment]
@ashu8786 I didn't do anything special for this issue.
But, since I delivered the latest version of our application, it has not occurred (May 31, 2022).
I don't know if it's because the affected users no longer use the application or if updating the application's libraries fixed the problem.

In the prod application :
react-native version: 0.68.2
react-native-webview version: 11.8.2

**Comment by jayanta-hub** [comment]
I am also getting same issue only in android 12. (Samsung M31s and Redmi Note 10 pro). Please let us known if anyone find any solution .  

In the prod application :
react-native version: 0.68.2
react-native-webview version: 11.8.2

**Comment by yoyo0427** [comment]
set the style of WebView to opacity: 0.99

**Comment by muneerhasanandroid** [comment]
getting same issue, any update?

**Comment by ybwdaisy** [comment]
+1
