### ISSUE TITLE
sdk_gwear_g3_x86 issue when using Google Play Store

### ISSUE THREAD

**Issue by billnbell** [react-native-webview/react-native-webview#2670]
I am getting this crash on sdk_gwear_g3_x86 when Google tries to load my app.

```
Fatal Exception: java.lang.UnsupportedOperationException
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:242)
       at android.webkit.CookieManager.getInstance(CookieManager.java:50)
       at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:136)
       at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:53)
       at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.kt:47)
       at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:44)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:74)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by billnbell** [comment]
Version:Android 11

**Comment by billnbell** [comment]
By the way in Firebase what is sdk_gwear_g3_x86 ?

**Comment by JordaoViktor** [comment]
@billnbell  did you solved this error?

**Comment by billnbell** [comment]
I did - by downgrading to very old Firebase in Android and excluding all Watches in the Google play store.

**Comment by Epick362** [comment]
Still getting this error reported. I do not want to support watches but this error could be handled soflty instead.
