### ISSUE TITLE
Calling View methods on another thread than the UI thread

### ISSUE THREAD

**Issue by beqramo** [react-native-webview/react-native-webview#2948]
**Bug description:**

Hi devs,
Android app is getting crashed when I'm trying to open Webview.
The strangest thing is that it doesn't work on the old branch, where everything was perfect before release.

I found a similar issue here but it is closed and there is no help from there too. 
https://github.com/react-native-webview/react-native-webview/issues/2695

**To Reproduce:**
Install the package on  react native and run it on an Android emulator.
the Android API versions I tested were 32 and 28.

**Expected behavior:**

it shouldn't crash the app

**Screenshots/Videos:**

<img width="516" alt="Screenshot 2023-05-05 at 1 23 05 PM" src="https://user-images.githubusercontent.com/40486471/236456910-128e7be9-8bbe-4dcd-942b-4dbc0f673418.png">

**Environment:**
 - OS: android
 - OS version: I think on all API but what i saw it is on 32 and 28
 - react-native version: 0.68.2
 - react-native-webview version: ^11.26.0 (I updated on a latest version but still same result)

here is a full crash log:

```bash
FATAL EXCEPTION: mqt_native_modules
Process: com.*, PID: 8437
java.lang.IllegalStateException: Calling View methods on another thread than the UI thread.
	at com.android.webview.chromium.WebViewChromium.b(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:2)
	at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:15)
	at android.webkit.WebView.<init>(WebView.java:443)
	at android.webkit.WebView.<init>(WebView.java:363)
	at android.webkit.WebView.<init>(WebView.java:345)
	at android.webkit.WebView.<init>(WebView.java:332)
	at android.webkit.WebView.<init>(WebView.java:322)
	at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebView.<init>(RNCWebViewManager.java:1557)
	at com.reactnativecommunity.webview.RNCWebViewManager.createRNCWebViewInstance(RNCWebViewManager.java:186)
	at com.reactnativecommunity.webview.RNCWebViewManager.createViewInstance(RNCWebViewManager.java:192)
	at com.reactnativecommunity.webview.RNCWebViewManager.createViewInstance(RNCWebViewManager.java:129)
	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:76)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Comment by mhumza37dev** [comment]
same crash, on both Emulator and Real device.

**Comment by beqramo** [comment]
It is shown in Google's pre-launch report too.
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/40486471/236688119-8ccd1c86-18d9-4c7f-b248-8310184d85b9.png">

**Comment by ologunomolade** [comment]
I have been facing same issue since two days ago, and the strange thing is that it was working before. just started happening out of the blue with zero changes to code...

**Comment by SandraBLOK** [comment]
the same story for me. Started to crash 3 days ago. Appreciate any help in resolving the issue!

**Comment by EvertV** [comment]
Same here. Only on Android, with `react-native-webview` v11.23.1 & RN v0.66.5

**Comment by Joels-code** [comment]
Same issue.
react-native v0.67.2
react-native-webview v11.23.1. 

I also tried updating react-native-webview to v12.0.2, and it still crashes. 

The weird thing is some previous app builds using the same version of react-native-webview (v11.23.1) do not crash.

**Comment by dannyhw** [comment]
was anyone able to find a workaround? Or the source of the problem?

**Comment by ologunomolade** [comment]
@dannyhw  still no solution or workaround  in my case.

**Comment by genelsa** [comment]
I have the same issue. Is there any solution?

**Comment by beqramo** [comment]
I have updated the entire project to RN 0.71 but still has the same bug.

**Comment by beqramo** [comment]
I found the issue,
for my case, it was coming from the customer io package:
https://github.com/customerio/customerio-reactnative/tree/main
I removed it and now it works

**Comment by Joels-code** [comment]
@beqramo I could get around this just by disabling in-app messaging for customer-io via the initialization instead of removing the entire package.

```
data.enableInApp = false;
CustomerIO.initialize(env, data);
```

I'm reaching out to the CustomerIO team, hoping to resolve this issue.

**Comment by beqramo** [comment]
Yes, already opened an issue.
Disabling can work too yes

**Comment by chenweigh** [comment]
react-native-webview:13.3.1 


I have the same issue. Is there any solution?
