### ISSUE TITLE
Opening a link with a data: scheme URL (inline file) does not work

### ISSUE THREAD

**Issue by vitexikora** [react-native-webview/react-native-webview#3251]
**Bug description:**
Clicking on a link in a WebView with a data: uri, such as this one:

```html
<a href="data:text/x-vcard;charset=utf-8;base64,QkVHSU46VkNBUkQKVkVSU0lPTjozLjAKRk47Q0hBUlNFVD1VVEYtODpBbmnEjWthCk47Q0hBUlNFVD1VVEYtODo7QW5pxI1rYTs7OwpFTUFJTDtDSEFSU0VUPVVURi04O3R5cGU9V09SSyxJTlRFUk5FVDprYWRsY2tvdmFAc292YW5ldC5jegpURUw7VFlQRT1XT1JLLFZPSUNFOis0MjA5OTk4ODg3NwpUSVRMRTtDSEFSU0VUPVVURi04OkN2acSNaXRlbGthIGLEm2x1aApPUkc7Q0hBUlNFVD1VVEYtODpHWiBNZWRpYVwsIGEucy4KUkVWOjIwMjMtMTItMDZUMTY6Mzc6NDEuNjMwWgpFTkQ6VkNBUkQK">
     Download VCF
</a>
```

Does apparently nothing. It is absolutely ignored, but in a full browser, a VCF file gets downloaded.
However, this gets logged to logcat:

```
W RNCWebViewManagerImpl: Unsupported URI, aborting download
W RNCWebViewManagerImpl: java.lang.IllegalArgumentException: Can not handle uri:: data:text/x-vcard;charset=utf-8;base64,QkVHSU46VkNBUkQKVkVSU0lPTjozLjAKRk47Q0hBUlNFVD1VVEYtODpBbmnEjWthCk47Q0hBUlNFVD1VVEYtODo7QW5pxI1rYTs7OwpFTUFJTDtDSEFSU0VUPVVURi04O3R5cGU9V09SSyxJTlRFUk5FVDprYWRsY2tvdmFAc292YW5ldC5jegpURUw7VFlQRT1XT1JLLFZPSUNFOis0MjA5OTk4ODg3NwpUSVRMRTtDSEFSU0VUPVVURi04OkN2acSNaXRlbGthIGLEm2x1aApPUkc7Q0hBUlNFVD1VVEYtODpHWiBNZWRpYVwsIGEucy4KUkVWOjIwMjMtMTItMDZUMTY6Mzc6NDEuNjMwWgpFTkQ6VkNBUkQK
W RNCWebViewManagerImpl:         at android.app.DownloadManager$Request.checkUri(DownloadManager.java:787)
W RNCWebViewManagerImpl:         at android.app.DownloadManager$Request.<init>(DownloadManager.java:770)
W RNCWebViewManagerImpl:         at com.reactnativecommunity.webview.RNCWebViewManagerImpl.createViewInstance$lambda-1(RNCWebViewManagerImpl.kt:97)
W RNCWebViewManagerImpl:         at com.reactnativecommunity.webview.RNCWebViewManagerImpl.$r8$lambda$gH_tTZLrblOtKn53LKimRKV1Rps(Unknown Source:0)
W RNCWebViewManagerImpl:         at com.reactnativecommunity.webview.RNCWebViewManagerImpl$$ExternalSyntheticLambda0.onDownloadStart(Unknown Source:9)
W RNCWebViewManagerImpl:         at WV.D6.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-604516433:483)
W RNCWebViewManagerImpl:         at android.os.Handler.dispatchMessage(Handler.java:106)
W RNCWebViewManagerImpl:         at android.os.Looper.loopOnce(Looper.java:211)
W RNCWebViewManagerImpl:         at android.os.Looper.loop(Looper.java:300)
W RNCWebViewManagerImpl:         at android.app.ActivityThread.main(ActivityThread.java:8401)
W RNCWebViewManagerImpl:         at java.lang.reflect.Method.invoke(Native Method)
W RNCWebViewManagerImpl:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
W RNCWebViewManagerImpl:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

I tried various configurations of WebView component props, but nothing seemed to help.

This is one example:
```jsx
      <WebView
          // startInLoadingState
          ref={webViewRef}
          source={source}
          injectedJavaScript={script}
          originWhitelist={['*']}
          allowFileAccessFromFileURLs
          allowUniversalAccessFromFileURLs
          onShouldStartLoadWithRequest={() => console.log('never gets called')}
          onNavigationStateChange={() => console.log('never gets called')}
      />
```

**To Reproduce:**
1. Load a page to a webview, containg the link above. 
2. Click on it.

**Expected behavior:**
A VCF file gets opened or downloaded.

**Environment:**
 - OS: Android
 - OS version: 13.0
 - react-native version: 0.72.3
 - react-native-webview version: 13.6.2 (also in 13.3.1)

**Side note:**
If there is a way an application running inside a webview can locally generate a file to be downloaded to the device running the webview, can you please guide me to it?

**Comment by robpearlman** [comment]
I have weirdly just come across the same bug in iOS using 13.6.0 trying to generate in the webview a .ics file

**Comment by vitexikora** [comment]
We are still waiting and counting on this being fixed sometime in the future! We now have ~10 client mobile web-view applications with a broken export button...

**Comment by vitexikora** [comment]
This is an open bug! The Webview experience should be the same as a browser and there is no reason for this not to work.

**Comment by vitexikora** [comment]
Are there any plans to make this work?

**Comment by vitexikora** [comment]
This is not completed at all.
