### ISSUE TITLE
WebView Crashing 

### ISSUE THREAD

**Issue by asutariyadigit** [react-native-webview/react-native-webview#3383]
Hi My App crashing the below Error:
com.facebook.react.views.view.ReactClippingViewManager.getChildCount
java.lang.ClassCastException - com.reactnativecommunity.webview.d cannot be cast to com.facebook.react.views.view.ReactViewGroup

**To Reproduce:** if we Continue move between From Webview to View Component  by Pressing hardware back button.

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:MacOS 14.2.1
 - OS version:
 - react-native version:0.70.6
 - react-native-webview version: "react-native-webview": "^13.2.2",

Fatal Exception: java.lang.ClassCastException: com.reactnativecommunity.webview.d cannot be cast to com.facebook.react.views.view.ReactViewGroup
       at com.facebook.react.views.view.ReactClippingViewManager.getChildCount()
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:70)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.dropView(ReanimatedNativeHierarchyManager.java:7)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:104)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.dropView(ReanimatedNativeHierarchyManager.java:7)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:104)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.dropView(ReanimatedNativeHierarchyManager.java:7)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:104)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.dropView(ReanimatedNativeHierarchyManager.java:7)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:104)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.dropView(ReanimatedNativeHierarchyManager.java:7)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:104)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.dropView(ReanimatedNativeHierarchyManager.java:7)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:104)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.dropView(ReanimatedNativeHierarchyManager.java:7)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:104)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.dropView(ReanimatedNativeHierarchyManager.java:7)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:104)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.dropView(ReanimatedNativeHierarchyManager.java:7)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:304)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:13)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:14)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:135)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:53)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:46)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1140)
       at android.view.Choreographer.doCallbacks(Choreographer.java:946)
       at android.view.Choreographer.doFrame(Choreographer.java:870)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8292)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by netmaxt3r** [comment]
@asutariyadigit looks like you have reanimated , can you post your jsx view hierarchy?

**Comment by asutariyadigit** [comment]
<View style={{ marginTop: StatusBar.currentHeight, marginBottom: 0 }}>
          <Header
            homeScreen={true}
            navigateHome={true}
            isProgressBarShown={false}
            leftActionPress={() => {
              this.props.navigation.openDrawer();
            }}
          />
        </View>

        <StatusBar
          barStyle="dark-content"
          hidden={false}
          backgroundColor="#ffffff"
          translucent={true}
        />
        <WebView
          ref={(ref) => (this.WEBVIEW_REF = ref)}
          source={{ uri: redirectionLink }}
          onNavigationStateChange={(event) =>{
            var url = event.url;
            this.onNavigationStateChange(event);
              if(url.includes("/KYC")){
              this.props.navigation.navigate("KYCScreen", {kycUrl : url, flow : 'Car Insurance', data : this.state.afData });
            }
          }
        }
          javaScriptEnabledAndroid={true}
          javaScriptEnabled={true}
          automaticallyAdjustContentInsets={false}
          startInLoadingState={true}
         androidHardwareAccelerationDisabled={true}
          allowsBackForwardNavigationGestures={true}

**Comment by asutariyadigit** [comment]
![WhatsApp Image 2024-04-06 at 1 10 46 AM](https://github.com/react-native-webview/react-native-webview/assets/153620792/31cef2e7-840b-496b-9137-9798b7d7cb80)
![Uploading WhatsApp Image 2024-04-07 at 1.52.23 PM.jpeg…]()

**Comment by asutariyadigit** [comment]
@netmaxt3r @alloy  Please any solution?

**Comment by netmaxt3r** [comment]
@asutariyadigit i am not able to reproduce the issue with code you have provided works fine with bare project and your code ( with minor modifications ). the root cause must be somewhere else, with your higher wrapping components. where does your `View` import is from? is it animated View ? if yes try changing to `View` from `react-native`

**Comment by asutariyadigit** [comment]
@netmaxt3r  Thanks for your response View is not imported from animated view it is taken only View from react-native.

**Comment by netmaxt3r** [comment]
> if we Continue move between From Webview to View Component by Pressing hardware back button

that suggests you need to look into your navigation setup, try turn off any animation you have between screen navigation, update reanimated library and check

**Comment by asutariyadigit** [comment]
Hi @netmaxt3r stop animation  in Stack navigator as well individual  component.

**Comment by asutariyadigit** [comment]
@netmaxt3r  Any  Solution for that.

**Comment by eth-jashan** [comment]
@asutariyadigit  did you find anything around it. Have been getting this as crash issue in react-native-webview

**Comment by asutariyadigit** [comment]
Hi @eth-jashan But we do not find exact root cause.

**Comment by eth-jashan** [comment]
@asutariyadigit  but were you able to solve or anything ?

**Comment by netmaxt3r** [comment]
@eth-jashan @asutariyadigit  can anyone of you provide a full code repo to reproduce this issue?
