### ISSUE TITLE
RN WebView Crashes with ClassCastException

### ISSUE THREAD

**Issue by rohanp-91** [react-native-webview/react-native-webview#3431]
**Bug description:**
I am using a POST when loading the source in Android RN WebView. This POST returns a 302 and does a redirect to another URL. After that, I am seeing the following crash:

`Exception in native call
                                                                                                    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
                                                                                                    	at com.facebook.react.bridge.ReadableNativeArray.getBoolean(ReadableNativeArray.java:87)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper$1.extractArgument(JavaMethodWrapper.java:37)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper$1.extractArgument(JavaMethodWrapper.java:33)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:356)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)`

I tried to debug through the external code as well and I saw that it's trying to parse the redirect URL, which is obviously a string, as a Boolean.

**To Reproduce:**
I am just sharing the code I have:

<WebView
        ref={this.webref}
        applicationNameForUserAgent={`${this.props.appName}/${this.props.appVersion}`}
        source={{
           uri: `https://abc.com?rurl=${encodeURIComponent(redirectUrl)}`,
           headers: Platform.OS === 'ios' ? {
               'Content-Type': 'application/x-www-form-urlencoded',
            } : '',
            body: `Authorization=${accessToken}`,
            method: 'POST',
        }}
        sharedCookiesEnabled={true}
        onError={this.onError}
        onHttpError={this.onHttpError}
        onLoadStart={this.onLoadStart}
        onLoadEnd={this.onLoadEnd}
        onNavigationStateChange={this.onNavigationStateChange}
        onRenderProcessGone={this.onRenderProcessGone}
        onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest}
        onMessage={this.onMessage}
        renderLoading={this.renderLoadingView(this.props.url)}
        startInLoadingState={true}
        mixedContentMode="always"
        androidLayerType="software"
        textZoom={100}
        originWhitelist={['*']}
        nativeConfig={{ props: { webContentsDebuggingEnabled: true } }}
        testID='webview'
        allowsBackForwardNavigationGestures={true}
        renderError={this.renderErrorView}
      />

**Expected behavior:**
There shouldn't be a ClassCastException being thrown. It should not try to parse the redirect URL as Boolean.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: API 33
 - react-native version: 0.70.7
 - react-native-webview version: 13.8.6

**Comment by rohanp-91** [comment]
The issue was with how we were getting the cookies. Some typo in the code, not an issue with WebView. Thanks!
