### ISSUE TITLE
WebView crashes on Android while opening the file chooser with RN v0.74 in bridgeless mode

### ISSUE THREAD

**Issue by jacobmllr95** [react-native-webview/react-native-webview#3474]
**Bug description:**

The WebView crashes on Android while opening the file chooser with the following message:

```bash
Handling uncaught Java exception
java.lang.IllegalStateException: Trying to call native module before CatalystInstance has been set!
	at com.facebook.react.bridge.ReactContext.raiseCatalystInstanceMissingException(ReactContext.java:154)
	at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:207)
	at com.reactnativecommunity.webview.RNCWebChromeClient.onShowFileChooser(RNCWebChromeClient.java:336)
	at WV.RZ.h(chromium-TrichromeWebViewGoogle6432.aab-stable-642216533:35)
	at WV.W8.runFileChooser(chromium-TrichromeWebViewGoogle6432.aab-stable-642216533:34)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

This only happens with RN v0.74 in bridgeless mode.
When bridgeless mode is disabled, as described [here](https://github.com/reactwg/react-native-new-architecture/discussions/174), everything works as expected.

This might be related to #3352.

**To Reproduce:**
- Load a website with a file input
- Click on the file input
- App / WebView crashes

**Expected behavior:**
- Load a website with a file input
- Click on the file input
- File chooser opens

**Environment:**
 - OS: Android
 - OS version: 14
 - react-native version: 0.74.2
 - react-native-webview version: 13.10.4

**Comment by moonoiza** [comment]
I got same issue and found out the cause.

`                                                                                                    Caused by: java.lang.IllegalStateException: Trying to call native module before CatalystInstance has been set!
                                                                                                    	at com.facebook.react.bridge.ReactContext.raiseCatalystInstanceMissingException(ReactContext.java:154)
                                                                                                    	at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:207)
                                                                                                    	at com.reactnativecommunity.webview.RNCWebChromeClient.onShowFileChooser(RNCWebChromeClient.java:336)`

So I inspected RNCWebChromeClient.java and found that it sill called getNativeModule() on architecture context.
You can use my patch to make your input=file work again.
[patch-webview.patch](https://github.com/user-attachments/files/16488018/patch-webview.patch)

**Comment by shovel-kun** [comment]
@moonoiza The patch only applied if I kept the changes in `RNCWebChromeClient.java`.

Would it be okay for you to submit a PR for this change?

**Comment by Kabeer10** [comment]
Any updates on this, How do i apply the patch ?

**Comment by vbansal-bb** [comment]
looks like this is fixed in RN version >=0.75.0 can not repro on neither 0.75.4 (on new architecture on bridgeless) and on 0.76.1 (on default i.e on new architecture) as well
