### ISSUE TITLE
ANR in drawing webview

### ISSUE THREAD

**Issue by cw-saurav** [react-native-webview/react-native-webview#3486]
**Bug description:**
at J.N.MTXp4fn_(Native method)
at WV.x6.onDraw(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:227)
at com.android.webview.chromium.WebViewChromium.onDraw(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:40)
at android.webkit.WebView.onDraw(WebView.java:2956)
at android.view.View.draw(View.java:24728)
at android.view.View.updateDisplayListIfDirty(View.java:23520)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)
at android.view.View.updateDisplayListIfDirty(View.java:23445)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4668)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4641)

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: all 
 - OS version: all 
 - react-native version: 0.73.6
 - react-native-webview version: 13.8.1

**Comment by gontovnik** [comment]
We're seeing a large increase in ANRs as well, starting 1-2 weeks ago. We had this package for a long time though.

**Comment by jianglei12138** [comment]
https://issuetracker.google.com/issues/349274976
