### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by rahul8844** [react-native-webview/react-native-webview#3488]
some crashes reported in our prod app, tried to reproduce it but not able to, also these crashes are not consistent in behaviour.  
 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
       at com.reactnativecommunity.webview.e.onReceivedSslError(RNCWebViewClient.java:12)
       at WV.Q6.run(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:187)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
**Environment:**
 - OS version: > 8
 - react-native version: v0.71.13
 - react-native-webview version: 13.6.2

**Comment by hyejin-1010** [comment]
@rahul8844 Hi, sorry for commenting on a closed issue.

We recently received the same crash report in our crash analytics with the same stack trace (RNCWebViewClient.onReceivedSslError → NullPointerException).

I noticed this issue was closed without a clear resolution. Were you able to resolve it on your side?

If so, could you share what the cause or workaround was?

Thank you!
