### ISSUE TITLE
WebView crashes on Android while opening the file chooser

### ISSUE THREAD

**Issue by Virajmakwana** [react-native-webview/react-native-webview#3558]
**Bug description:**
The WebView crashes on Android while opening the file chooser with the following message:

org.chromium.base.JniAndroid$UncaughtExceptionException: Native stack trace:
#00 pc 0x0000000007214ed7 /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#01 pc 0x0000000005f03797 /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#02 pc 0x000000000299babf /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#03 pc 0x0000000003998437 /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#04 pc 0x00000000039896ef /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#05 pc 0x00000000033e0337 /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#06 pc 0x00000000060efd37 /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#07 pc 0x00000000060eab47 /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#08 pc 0x0000000005d52203 /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#09 pc 0x00000000060ef007 /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#10 pc 0x00000000060ebf23 /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#11 pc 0x00000000047c82c3 /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#12 pc 0x00000000047e7c9f /data/app/~~7YzLtp2byysRYezhPNRRiA==/com.google.android.trichromelibrary_661312733-jRsTESL_yFNXcOdPNvE6Gg==/base.apk (offset 0x8dc000)
#13 pc 0x0000000000009b6f /system/lib64/libutils.so
#14 pc 0x0000000000009627 /system/lib64/libutils.so
#15 pc 0x00000000000accab /system/lib64/libandroid_runtime.so

        at org.chromium.base.JniAndroid.handleException(chromium-TrichromeWebViewGoogle6432.aab-stable-661312733:21)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:350)
        at android.os.Looper.loopOnce(Looper.java:187)
        at android.os.Looper.loop(Looper.java:368)
        at android.app.ActivityThread.main(ActivityThread.java:8848)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.IllegalStateException: Trying to call native module before CatalystInstance has been set!
        at com.facebook.react.bridge.ReactContext.raiseCatalystInstanceMissingException(ReactContext.java:154)
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:207)
        at com.reactnativecommunity.webview.RNCWebChromeClient.onShowFileChooser(RNCWebChromeClient.java:336)
        at WV.QX.j(chromium-TrichromeWebViewGoogle6432.aab-stable-661312733:35)
        at WV.m9.runFileChooser(chromium-TrichromeWebViewGoogle6432.aab-stable-661312733:34)
        ... 8 more

**To Reproduce:**

- Load a website with a file input
- Click on the file input
- App / WebView crashes

**Expected behavior:**

- Load a website with a file input
- Click on the file input
- File chooser opens

**Environment:**
 - OS: Android
 - OS version: 14
 - react-native version: 0.74.5
 - react-native-webview version: 13.10.4

**Comment by Enrolify** [comment]
Did anyone get fix for this ?

**Comment by Kabeer10** [comment]
Did anyone get fix for this ?

**Comment by labmember003** [comment]
Any fixes?

**Comment by cw-bhuvaneshtrivedi** [comment]
Any fixes?
